

services:
  backend:
    build: 
      context: ./backend
    container_name: go-backend
    ports:
      - "8080:8080"
    working_dir: /app
    command: ["./app"]

  frontend:
    build:
      context: ./frontend/minekrep
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
